[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "catch section cram safe try sorry demand blouse material curve hybrid snack weekend grow suffer faculty lottery crater arch review love window total bean"
